language: java
sudo: false
#Las pruebas deben ser pasadas, cuando tengamos las pruebas.
script: mvn clean install -DskipTests=true
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
notifications:
  email:
    recipients:
	- haniel@hanielma.com
    on_success: never
    on_failure: always
